language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
  - "mv settings/config.json.example settings/config.json"
  - "python run.py"