const util = {};

util.httpErrors = {
    // 1xx
    100: "Continue",
    101: "Switching Protocols",
    102: "Server has received and is processing the request",
    103: "Early Hints",
    122: "URI is longer than a maximum of 2083 characters",
    // 2xx
    200: "OK",
    201: "Created",
    202: "Accepted",
    203: "Non-Authoritative Information",
    204: "No Content",
    205: "Reset Content",
    206: "Partial Content",
    207: "XML return with possible multiple seperate responses.",
    208: "The results are previously returned.",
    226: "The request has been fulfilled and response is in instance manipulations.",
    // 3xx
    300: "Multiple Choice",
    301: "Moved Permanently",
    302: "Found",
    303: "See Other",
    304: "Not Modified",
    305: "Use Proxy",
    306: "UNUSED/UNKNOWN STATUS CODE",
    307: "Temporary Redirect",
    308: "Please connect again to the different URL using the same method.",
    // 4xx
    400: "Bad Request",
    401: "Unauthorized",
    402: "Payment Required",
    403: "Forbidden",
    404: "Not Found",
    405: "Method Not Allowed",
    406: "Not Acceptable",
    407: "Proxy Authentication Required",
    408: "Request Timeout",
    409: "Conflict",
    410: "Gone",
    411: "Length Required",
    412: "Precondition Failed",
    413: "Payload Too Large",
    414: "URI Too Long",
    415: "Unsupported Media Type",
    416: "Requested Range Not Supported",
    417: "Expectation Failed",
    418: "I'm a teapot.",
    420: "Method Failure",
    421: "Misdirected Request",
    422: "Unprocessable Entity",
    423: "Locked",
    424: "Failed Dependency",
    426: "Upgrade Required",
    428: "Precondition Required",
    429: "Too Many Requests",
    431: "Request Header Fields Too Large",
    440: "Login Timeout (Microsoft)",
    444: "No Response (Nginx)",
    449: "Retry With (Microsoft)",
    450: "Blocked by Windows Parental Controls",
    451: "Unavailable For Legal Reasons",
    494: "Request Header Too Large (Nginx)",
    495: "Cert Error (Nginx)",
    496: "No Cert (Nginx)",
    497: "HTTP to HTTPS (Nginx)",
    499: "Client Closed Request (Nginx)",
    // 5xx
    500: "Internal Server Error",
    501: "Not Implemented",
    502: "Bad Gateway",
    503: "Service Unavailable",
    504: "Gateway Timeout",
    505: "HTTP Version Not Supported",
    506: "Variant Also Negotiates (RFC 2295)",
    507: "Insufficient Storage (WebDAV; RFC 4918)",
    508: "Loop Detected (WebDAV; RFC 5842)",
    509: "Bandwidth Limit Exceeded (Apache bw/limited extension)",
    510: "Not Extended (RFC 2774)",
    511: "Network Authentication Required",
    520: "Web server is returning an unknown error (Cloudflare)",
    521: "Web server is down (Cloudflare)",
    522: "Connection timed out (Cloudflare)",
    523: "Origin is unreachable (Cloudflare)",
    524: "A timeout occurred (Cloudflare)",
    525: "SSL handshake failed (Cloudflare)",
    526: "Invalid SSL certificate (Cloudflare)",
    599: "Network Connect Timeout"

};

module.exports = util;